SHOPPERTRAK_SITES = set(
    [
        "ag",
        "al",
        "ba",
        "bc",
        "be",
        "bl",
        "bl - teen_center; interior",
        "br",
        "bt",
        "ca",
        "ch",
        "ci",
        "cl",
        "cn",
        "cp",
        "cs",
        "ct",
        "dh",
        "dy",
        "ea",
        "ep",
        "ew",
        "fe",
        "ft",
        "fw",
        "fx",
        "gd",
        "gd - teen_center; interior",
        "gk",
        "hb",
        "hb - teen_center; interior",
        "hd",
        "hf",
        "hg",
        "hk",
        "hl",
        "hp",
        "hs",
        "ht",
        "hu",
        "in",
        "jm",
        "jp",
        "kb",
        "kp",
        "lb",
        "lm",
        "ma - 40th_st_1",
        "ma - 40th_st_2",
        "ma - 42nd_st",
        "ma - 5th_ave",
        "ma - bartos; interior",
        "ma - gottesman; interior",
        "ma - retail; interior",
        "ma - social_sciences_library; interior",
        "ma - visitor_center; interior",
        "ma - wachenheim; interior",
        "mb",
        "mb - teen_center; interior",
        "me",
        "mh",
        "mh - teen_center; interior",
        "ml",
        "mn",
        "mo",
        "mp",
        "mr",
        "mu",
        "my",
        "nb",
        "nd",
        "ns",
        "ot",
        "pk",
        "pm",
        "pr",
        "rd",
        "ri",
        "rs",
        "rt",
        "sa",
        "sb",
        "sc",
        "sd",
        "se",
        "sg",
        "sg - teen_center; interior",
        "sn",
        "ss",
        "st",
        "sv",
        "tg",
        "th",
        "tm",
        "ts",
        "tv",
        "vc",
        "vn",
        "wb",
        "wf",
        "wh",
        "wk",
        "wl",
        "wo",
        "wt",
        "yv",
    ]
)
